name: Guile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install guile-3.0
      run: sudo apt-get install -y guile-3.0
    - name: Run tests
      run: make test | ( ! grep -E "^# of unexpected failures" )
